repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.7.1" # Use the sha / tag you want to point at
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@2.7.1
                - prettier-plugin-java@1.6.2
